version: "2"
linters:
  enable:
    - errcheck
    - staticcheck
    - gocritic
    - noctx

linters-settings:
  gocritic:
    enabled-tags:
      - diagnostic
      - style

issues:
  exclude-use-default: false