version: '3.8'

services:
  db:
    image: postgres:latest
    container_name: db
    ports:
      - "5432:5432"
    env_file:
      - .env
    volumes:
      - pg_data:/var/lib/postgresql/data
  redis:
    image: redis
    container_name: redis
    ports:
    - "6379:6379"
      
volumes:
  pg_data:
    driver: local