supported_coins = [
    {"id": "bitcoin", "symbol": "btc", "name": "Bitcoin"},
    {"id": "ethereum", "symbol": "eth", "name": "Ethereum"},
    {"id": "tether", "symbol": "usdt", "name": "Tether"},
    {"id": "binancecoin", "symbol": "bnb", "name": "BNB"},
    {"id": "usd-coin", "symbol": "usdc", "name": "USD Coin"},
    {"id": "ripple", "symbol": "xrp", "name": "XRP"},
    {"id": "binance-usd", "symbol": "busd", "name": "Binance USD"},
    {"id": "dogecoin", "symbol": "doge", "name": "Dogecoin"},
    {"id": "cardano", "symbol": "ada", "name": "Cardano"},
    {"id": "solana", "symbol": "sol", "name": "Solana"},
    {"id": "matic-network", "symbol": "matic", "name": "Polygon"},
    {"id": "polkadot", "symbol": "dot", "name": "Polkadot"},
    {"id": "staked-ether", "symbol": "steth", "name": "Lido Staked Ether"},
    {"id": "shiba-inu", "symbol": "shib", "name": "Shiba Inu"},
    {"id": "avalanche-2", "symbol": "avax", "name": "Avalanche"},
    {"id": "tron", "symbol": "trx", "name": "TRON"},
    {"id": "uniswap", "symbol": "uni", "name": "Uniswap"},
    {"id": "dai", "symbol": "dai", "name": "Dai"},
    {"id": "okb", "symbol": "okb", "name": "OKB"},
    {"id": "wrapped-bitcoin", "symbol": "wbtc", "name": "Wrapped Bitcoin"},
    {"id": "litecoin", "symbol": "ltc", "name": "Litecoin"},
    {"id": "cosmos", "symbol": "atom", "name": "Cosmos Hub"},
    {"id": "chainlink", "symbol": "link", "name": "Chainlink"},
    {"id": "leo-token", "symbol": "leo", "name": "LEO Token"},
    {"id": "ethereum-classic", "symbol": "etc", "name": "Ethereum Classic"},
    {"id": "ftx-token", "symbol": "ftt", "name": "FTX"},
    {"id": "crypto-com-chain", "symbol": "cro", "name": "Cronos"},
    {"id": "algorand", "symbol": "algo", "name": "Algorand"},
    {"id": "stellar", "symbol": "xlm", "name": "Stellar"},
    {"id": "monero", "symbol": "xmr", "name": "Monero"},
    {"id": "near", "symbol": "near", "name": "NEAR Protocol"},
    {"id": "the-open-network", "symbol": "ton", "name": "The Open Network"},
    {"id": "bitcoin-cash", "symbol": "bch", "name": "Bitcoin Cash"},
    {"id": "quant-network", "symbol": "qnt", "name": "Quant"},
    {"id": "filecoin", "symbol": "fil", "name": "Filecoin"},
    {"id": "flow", "symbol": "flow", "name": "Flow"},
    {"id": "vechain", "symbol": "vet", "name": "VeChain"},
    {"id": "terra-luna", "symbol": "lunc", "name": "Terra Luna Classic"},
    {"id": "apecoin", "symbol": "ape", "name": "ApeCoin"},
    {"id": "hedera-hashgraph", "symbol": "hbar", "name": "Hedera"},
    {"id": "internet-computer", "symbol": "icp", "name": "Internet Computer"},
    {"id": "chiliz", "symbol": "chz", "name": "Chiliz"},
    {"id": "elrond-erd-2", "symbol": "egld", "name": "Elrond"},
    {"id": "the-sandbox", "symbol": "sand", "name": "The Sandbox"},
    {"id": "aave", "symbol": "aave", "name": "Aave"},
    {"id": "tokenize-xchange", "symbol": "tkx", "name": "Tokenize Xchange"},
    {"id": "tezos", "symbol": "xtz", "name": "Tezos"},
    {"id": "decentraland", "symbol": "mana", "name": "Decentraland"},
    {"id": "theta-token", "symbol": "theta", "name": "Theta Network"},
    {"id": "lido-dao", "symbol": "ldo", "name": "Lido DAO"},
    {"id": "frax", "symbol": "frax", "name": "Frax"},
    {"id": "eos", "symbol": "eos", "name": "EOS"},
    {"id": "axie-infinity", "symbol": "axs", "name": "Axie Infinity"},
    {"id": "chain-2", "symbol": "xcn", "name": "Chain"},
    {"id": "huobi-token", "symbol": "ht", "name": "Huobi"},
    {"id": "aptos", "symbol": "apt", "name": "Aptos"},
    {"id": "kucoin-shares", "symbol": "kcs", "name": "KuCoin"},
    {"id": "whitebit", "symbol": "wbt", "name": "WhiteBIT Token"},
    {"id": "bitcoin-cash-sv", "symbol": "bsv", "name": "Bitcoin SV"},
    {"id": "paxos-standard", "symbol": "usdp", "name": "Pax Dollar"},
    {"id": "true-usd", "symbol": "tusd", "name": "TrueUSD"},
    {"id": "maker", "symbol": "mkr", "name": "Maker"},
    {"id": "osmosis", "symbol": "osmo", "name": "Osmosis"},
    {"id": "bittorrent", "symbol": "btt", "name": "BitTorrent"},
    {"id": "compound-usd-coin", "symbol": "cusdc", "name": "cUSDC"},
    {"id": "iota", "symbol": "miota", "name": "IOTA"},
    {"id": "gemini-dollar", "symbol": "gusd", "name": "Gemini Dollar"},
    {"id": "ecash", "symbol": "xec", "name": "eCash"},
    {"id": "arweave", "symbol": "ar", "name": "Arweave"},
    {"id": "the-graph", "symbol": "grt", "name": "The Graph"},
    {"id": "fantom", "symbol": "ftm", "name": "Fantom"},
    {"id": "usdd", "symbol": "usdd", "name": "USDD"},
    {"id": "klay-token", "symbol": "klay", "name": "Klaytn"},
    {"id": "zcash", "symbol": "zec", "name": "Zcash"},
    {"id": "pancakeswap-token", "symbol": "cake", "name": "PancakeSwap"},
    {"id": "gatechain-token", "symbol": "gt", "name": "Gate"},
    {"id": "ethereum-pow-iou", "symbol": "ethw", "name": "EthereumPoW"},
    {"id": "evmos", "symbol": "evmos", "name": "Evmos"},
    {"id": "havven", "symbol": "snx", "name": "Synthetix Network"},
    {"id": "neo", "symbol": "neo", "name": "NEO"},
    {"id": "btse-token", "symbol": "btse", "name": "BTSE Token"},
    {"id": "compound-ether", "symbol": "ceth", "name": "cETH"},
    {"id": "cdai", "symbol": "cdai", "name": "cDAI"},
    {"id": "nexo", "symbol": "nexo", "name": "NEXO"},
    {"id": "curve-dao-token", "symbol": "crv", "name": "Curve DAO"},
    {"id": "helium", "symbol": "hnt", "name": "Helium"},
    {"id": "mina-protocol", "symbol": "mina", "name": "Mina Protocol"},
    {"id": "radix", "symbol": "xrd", "name": "Radix"},
    {"id": "thorchain", "symbol": "rune", "name": "THORChain"},
    {"id": "pax-gold", "symbol": "paxg", "name": "PAX Gold"},
    {"id": "trust-wallet-token", "symbol": "twt", "name": "Trust Wallet"},
    {"id": "dash", "symbol": "dash", "name": "Dash"},
    {"id": "basic-attention-token", "symbol": "bat", "name": "Basic Attention"},
    {"id": "zilliqa", "symbol": "zil", "name": "Zilliqa"},
    {"id": "enjincoin", "symbol": "enj", "name": "Enjin Coin"},
    {"id": "frax-share", "symbol": "fxs", "name": "Frax Share"},
    {"id": "celsius-degree-token", "symbol": "cel", "name": "Celsius Network"},
    {"id": "kava", "symbol": "kava", "name": "Kava"},
    {"id": "bitdao", "symbol": "bit", "name": "BitDAO"},
    {"id": "ethereum-name-service", "symbol": "ens", "name": "Ethereum Name Service"},
]
